framework:
    default_locale: '%locale%'
    translator:
        paths:
            - '%kernel.project_dir%/translations/en'
            - '%kernel.project_dir%/translations/pl'
        fallbacks: ['en','pl']
